#ifndef EVENT_H
#define EVENT_H

enum Event
{
	NoEventOccured, //0
	EV_SCHUTSTART,
	EV_EMERGENCY,
	EV_RESUME,
	EV_RIGHTDOOROPENED,
	EV_RIGHTDOORCLOSED, //5
	EV_LEFTDOOROPENED,
	EV_LEFTDOORCLOSED,
	EV_WATER_LOW,
	EV_WATER_HIGH,
	EV_DOORSHALTED, //10
	EV_WATERLEVEL_ABOVE_VALVE2,
	EV_WATERLEVEL_ABOVE_VALVE3,
	EV_VALVESCLOSED,
	EV_BTNINVARENPRESSED,
	EV_BTNUITVARENPRESSED //15
};
#endif
